### ISSUE TITLE
Integration with kitchen-vagrant

### ISSUE THREAD

**Issue by zambon** [audiolize/vagrant-softlayer#4]
I'm trying to use [test-kitchen](https://github.com/test-kitchen/test-kitchen), with the [kitchen-vagrant](https://github.com/test-kitchen/kitchen-vagrant) driver and your vagrant-softlayer plugin. First, I created a `softlayer` box following the instructions you provided.

Then, I edited my `.kitchen.yml` file to look something like this:

```

---
driver:
  name: vagrant
  provider: softlayer
  customize:
    username: <%= ENV['SL_API_USERNAME'] %>
    api_key:  <%= ENV['SL_API_KEY'] %>
    # ...

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

# ...
```

The kitchen-vagrant driver parses that as the [Vagrant docs require](http://docs.vagrantup.com/v2/providers/configuration.html):

```
Vagrant.configure("2") do |config|
  config.vm.provider :softlayer do |sl|
    sl.customize ["modifyvm", :id, "--username", "..."]
    sl.customize ["modifyvm", :id, "--api_key", "..."]
    # ...
  end
end
```

But, at the same time, vagrant-softlayer expects something a little bit different:

```
Vagrant.configure("2") do |config|
  config.vm.provider :softlayer do |sl|
    sl.username = "..."
    sl.api_key  = "..."
    # ...
  end
end
```

The result is that none of the parameters specified in `.kitchen.yml` are applied correctly.  If I hardcode them in the `Vagrantfile`, Kitchen is able to read them. I'm not sure exactly where is the problem. Any thoughts?
